### ISSUE TITLE
can't compile Dofus-Injector to get the DLL

### ISSUE THREAD

**Issue by melharfi** [LuaxY/Dofus-Injector#1]
Hi

i can't compile the project
it told me that : 
C:\Users\the-m\Downloads\Compressed\Dofus-Injector-master\Dofus-Injector-master\src\AdminApi.as(19): col: 50 Error: Interface LuaPackage was not found.

and the word LuaPackage is underline with red it mean there's an error on it
public class AdminApi extends Object implements LuaPackage

 classe AdminApi.as Line 19

and the content of LuaPackage is empty : 
package com.ankamagames.jerakine.lua
{
    public interface LuaPackage
    {   }
}

is it normal ?

i just can't compile it

i find it very hard to create all process, compiling the dofus-injector dll and a third party injector foc dofus client, isn't there any tutorial of all steps how to patch the client 2.3x of dofus ?

thanks in advance

**Comment by LuaxY** [comment]
Hi,

This project don't generate DLL, it's .swf file to send with RawDataMessage.

Can you tell me what Dofus version and build type (release, debug) you are using ? Are you using the same Dofus API ??

About patching client, you have to do yourself with FFDec JPEXS by patching the code that block you.

**Comment by melharfi** [comment]
Hi

thank you to respond me,

well, i made a mistake, i confuse ankama.cpp with this one
but what was this Dofus-injector for ?

another thing to clarify my mind, what i've understaud is that it's not possible until now to patch dofus client 2.30 or higher, and then another trick is found by you i guess is injecting that ankama.dll

is it right or is there a patched DofusInvoker already existe only with JpexFF decompiler ?
because i folow your video tuto and it's does'nt work for the other version.

thank man for helping

**Comment by LuaxY** [comment]
The repo of DLL : https://github.com/LuaxY/No.Ankama
You can download DLL here : https://github.com/LuaxY/No.Ankama/releases

This project is to inject some code on Dofus instance, you can do what you what with client in AS3, this is just some sample what is possible to do ;)

Is still possible to patch Dofus 2.3x, Ankama have just added some code/protection that you have to manage. The video is old, some new protections exist now but the process is the same with JPEXS.

I don't think anyone had posted a patch publicly for 2.3x.
